import type { Request, Response } from "express";
import { asyncHandler } from "../utils/asyncHandler";
import { sendSuccess } from "../utils/apiResponses";
import * as aiService from "../services/ai.service";

// Creates an entire form schema with questions and theme generated by Gemini from a text prompt
export const generateForm = asyncHandler(
  async (req: Request, res: Response) => {
    const form = await aiService.generateForm(req.body.prompt);
    sendSuccess(res, {
      message: "Form generated",
      data: { form },
    });
  },
);

// Recommends regex patterns, limits, and error messages tailored to a question's type and label
export const generateValidation = asyncHandler(
  async (req: Request, res: Response) => {
    const validation = await aiService.generateValidation(req.body);
    sendSuccess(res, {
      message: "Validation suggested",
      data: { validation },
    });
  },
);

// Refines question wording for neutral tone and clarity, providing suggested follow-up questions
export const improveQuestion = asyncHandler(
  async (req: Request, res: Response) => {
    const result = await aiService.improveQuestion(req.body);
    sendSuccess(res, {
      message: "Question improved",
      data: { result },
    });
  },
);

// Summarizes form goals, identifies target audience, and gives concrete UX tips
export const formSummary = asyncHandler(async (req: Request, res: Response) => {
  const summary = await aiService.summarizeForm(req.body.form);
  sendSuccess(res, {
    message: "Summary ready",
    data: { summary },
  });
});
